### ISSUE TITLE
wrong json format (no comma at the end of the object)

### ISSUE THREAD

**Issue by arpitjha867** [gdscwce/Game-Facts-API#81]
https://github.com/gdscwce/Game-Facts-API/blob/3c3febe467837abd3d2628ead460c933d6735809/game-facts/minecraft.json#L112

**Comment by arpitjha867** [comment]
Assign this issue to me .

**Comment by arpitjha867** [comment]
Made a pull request for the same review it and merge it.

**Comment by RAOexe** [comment]
Sure

**Comment by arpitjha867** [comment]
I had already made the pull request and you merged it so I am closing the issue
