### ISSUE TITLE
New Endpoints

### ISSUE THREAD

**Issue by RAOexe** [gdscwce/Game-Facts-API#96]
Need endpoints:
1. One can request facts about more than one game but not compulsory all of the game i.e. functioning like Bitwise OR Operator. Endpoint could be like this game1 || game2

2. An endpoint which gives random fact about a game. Only one fact will be provided.

3. And endpoint which chooses random game and provides bunch of facts about that game.

**Comment by oxitheman** [comment]
Hey, the 1 and 2 have already been implemented in the api.

**Comment by RAOexe** [comment]
> Hey, the 1 and 2 have already been implemented in the latest merge. 

Nice 👍
Looking forward for the next PR!

**Comment by RAOexe** [comment]
Thanks @oxitheman ✨
