### ISSUE TITLE
feat: Update README.md with instructions on setup and usage of Virtual Environment

### ISSUE THREAD

**Issue by Ansh-Sarkar** [gdscwce/Game-Facts-API#99]
## Description

Virtual Environments are a great way of containerizing your code and making sure that you have a compatible development environment irrespective of whatever packages you may have on your local system. Virtual Environments in python help manage compatibility across different versions of the same package and enables faster setup via the ```requirements.txt``` file.

## Proposal

Proposal is to add detailed instructions as to how one can get started with their own virtual environment. This would not just help them setup this project, but also act as a best practice for future projects.

**Comment by RAOexe** [comment]
I think it's pretty much helpful...
Go ahead, I've assigned it to you only!
GL ✌️

**Comment by RAOexe** [comment]
> @RAOexe have raised a PR for this issue. Kindly do review it. Thanks !

Will review it no time!
Thanks 👍
